name: Build & Deploy May.la
on:
  push:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true
        fetch-depth: 0

    - name: Setup Hugo
      uses: peaceiris/actions-hugo@v2
      with:
        hugo-version: 'latest'
        extended: true

    - name: Setup Node
      uses: actions/setup-node@v3
      with:
        node-version: '14'

    # see https://stackoverflow.com/a/69984661
    # see https://docs.npmjs.com/cli/v8/commands/npm-ci
    # see https://github.com/peaceiris/actions-hugo#%EF%B8%8F-workflow-for-autoprefixer-and-postcss-clis
    - name: Install dependencies
#      run: npm ci
      run: npm i

    - name: Build
      run: hugo --minify

    - name: Upload Site
      uses: SamKirkland/FTP-Deploy-Action@2.0.0
      env:
        FTP_SERVER: www456.your-server.de
        FTP_USERNAME: eniaka_2
        FTP_PASSWORD: ${{ secrets.MAY_LA_FTP_PWD }}
        LOCAL_DIR: public
        METHOD: sftp
        PORT: 22
        ARGS: --delete
